# Project Information
site_name: Agentic Risk & Capability Framework
site_author: GovTech AI Practice
copyright: GovTech Singapore
docs_dir: docs
repo_url: https://github.com/govtech-responsibleai/agentic-risk-capability-framework/tree/gh-pages

# Theme Configuration
theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.expand
  palette:
    scheme: default
    primary: white
    accent: blue
  icon: 
    logo: material/shield-star
    favicon: material/shield-star

markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Extra CSS and JavaScript
extra_css:
  - https://unpkg.com/tabulator-tables@5.5.2/dist/css/tabulator_materialize.min.css

extra_javascript:
  - https://unpkg.com/tabulator-tables@5.5.2/dist/js/tabulator.min.js
  - assets/risk-register.js

# Extra Configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/govtech-responsibleai/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/govtech-singapore
    - icon: fontawesome/brands/twitter
      link: https://x.com/GovTechSG
  analytics:
    provider: google
    property: G-VDHLWLGZ1W
    feedback: 
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/KoXecxDuPHf8izP2A" target="_blank" rel="noopener">feedback form</a>.
    
# Navigation
nav:
  - ARC Framework:
    - index.md
    - Introduction: arc_framework/introduction.md
    - Elements of agentic systems: arc_framework/elements.md
    - Risks of agentic systems: arc_framework/risks.md
    - Controls for agentic systems: arc_framework/controls.md
    - Interactive Risk Register: arc_framework/risk-register.md
    - Comparison to other frameworks: arc_framework/comparison.md
  - Implementation:
    - Implementing ARC: implementation/index.md
    - For Governance Teams: implementation/for-governance-teams.md
    - For AI Developers: implementation/for-ai-developers.md
  - Resources:
    - resources/index.md
    - ARCvisor Tool: resources/arcvisor.md
# Plugins
plugins:
  - search
  - section-index
